### ISSUE TITLE
NotFoundError: No module named 'SocketServer'

### ISSUE THREAD

**Issue by brightersun99** [carter-yagemann/4ChanBBS#1]
Hi, this is broken. I tried it with python 2 and 3 

ip3 install -r requirements.txt 
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: python-aalib>=0.3.2 in /home/mother/.local/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (0.3.2)
Requirement already satisfied: telnetsrv>=0.4 in /home/mother/.local/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (0.4)
Requirement already satisfied: requests>=2.4.3 in /usr/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (2.24.0)
Requirement already satisfied: Pillow>=2.6.1 in /usr/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (7.2.0)
Requirement already satisfied: chardet>=3.0.2 in /usr/lib/python3.8/site-packages (from requests>=2.4.3->-r requirements.txt (line 3)) (3.0.4)
Requirement already satisfied: idna>=2.5 in /usr/lib/python3.8/site-packages (from requests>=2.4.3->-r requirements.txt (line 3)) (2.10)
Requirement already satisfied: urllib3>=1.21.1 in /usr/lib/python3.8/site-packages (from requests>=2.4.3->-r requirements.txt (line 3)) (1.25.10)

python Server.py 
Traceback (most recent call last):
  File "Server.py", line 22, in <module>
    import SocketServer
ModuleNotFoundError: No module named 'SocketServer'

uname -a:
Linux netnoob44.home 5.8.14-arch1-1 #1 SMP PREEMPT Wed, 07 Oct 2020 23:59:46 +0000 x86_64 GNU/Linux

python --version
Python 3.8.6

**Comment by brightersun99** [comment]
hi this is broken
can you make a disclaimer so people dont pollute their systems with these pip packages for a brokeb project?

**Comment by carter-yagemann** [comment]
This project still works with Python 2.7.16, which I just tested in a virtual environment. Supporting Python 3 is not easy due to a dependency on `telnetsrv`, which has not been updated in 8 years and only works with Python 2.x. I've updated the README.
